codecov:
  branch: master
  notify:
    require_ci_to_pass: no

coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 30%
        threshold: 10%

    patch:
      default:
        target: 1%
        threshold: 5%

    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/*.gradle"
  - "**/*.json"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no