dist: trusty
language: android

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "curious-coding"
    token:
      secure: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle/daemon'     #Cache daemon logs
    - '$HOME/.gradle/native'     #Cache library downloaded from the gradle dependency
    - '$HOME/.gradle/wrapper'    #Cache the gradle

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

jobs:
  include:
    - stage: Build
      name: Linting
      env: MAKETARGET=lint
    - name: Assemble
      env: MAKETARGET=assemble
    - name: Bundle
      env: MAKETARGET=bundle
    - name: Unit Test
      env: MAKETARGET=unit-test
    - name: Coverage Report
      env: MAKETARGET=report
    - name: Static Analysis
      script: sonar-scanner
script:
  - make clean $MAKETARGET
after_success:
  - bash <(curl -s https://codecov.io/bash)