name: Android App Template 🚀

on:
  pull_request:
    branches:
      - master

jobs:
  android-test:
    name: Android Test
    runs-on: macos-latest
    env:
      BUILD_TYPE: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: make android-test
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_REPO_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Linting
        run: make clean lint
      - name: Unit Test
        run: make clean unit-test
      - name: Report
        run: make clean report upload-coverage
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST: true
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: APK
        run: make clean assemble
      - name: Bundle
        run: make clean bundle
